#development:
#  sessions:
#   hosts:
#      - localhost:27017
#test:
#  sessions:
#    default:
#      uri: mongodb://marcoskata:ma123456@dbh61.mongolab.com:27617/series_jump_development
#      options:
#        consistency: :strong
#production:
#  sessions:
#    default:
#      uri: mongodb://marcoskata:ma123456@dbh61.mongolab.com:27617/series_jump_development
#      options:
#        skip_version_check: true
#        safe: true        
development:
  sessions:
    default:
      database: series_jump_development
      hosts:
        - localhost:27017
      options:
  options:
development:
  sessions:
    default:
      database: series_jump_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: series_jump_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
